# Generated by Django 4.0.5 on 2022-07-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadcam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('process', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('pg_name', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('type', models.CharField(max_length=10)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=200)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=200)),
            ],
        ),
    ]
