# Generated by Django 4.0.5 on 2022-07-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadcam',
            name='pqc_img',
            field=models.ImageField(blank=True, null=True, upload_to='PQC/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='cadcam',
            name='reason',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='cadcam',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cadcam',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='CAD_CAM/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='cadcam',
            name='process',
            field=models.CharField(choices=[('CNC3', 'CNC3'), ('CNC4', 'CNC4'), ('CNC5', 'CNC5'), ('CNC6', 'CNC6'), ('CNC7', 'CNC7'), ('CNC8', 'CNC8'), ('CNC9', 'CNC9')], max_length=50),
        ),
    ]
