# Generated by Django 4.0.5 on 2022-07-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_cadcam_pqc_img_cadcam_reason_cadcam_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadcam',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cadcam',
            name='status',
            field=models.CharField(default='Waiting', max_length=50),
        ),
    ]
