# Generated by Django 4.0.5 on 2022-07-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadcam',
            name='pqc_confirm_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cadcam',
            name='pqc_confirm_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
